# Infrastructure Deployment Pipeline
# Purpose: Deploy Azure infrastructure for portfolio project
# - Triggers only on infrastructure changes or manual runs
# - Deploys Bicep template to create all Azure resources
# - Outputs resource names/IDs for application pipeline consumption
# - Uses portfolio service connection for authentication

trigger:
  branches:
    include:
      - feature/infra-test
      - main
  paths:
    include:
      - infra/**
      - azure-pipelines-infra.yml

pr:
  branches:
    include:
      - staging
      - main
      - feature/*
  paths:
    include:
      - infra/**
      - azure-pipelines-infra.yml


variables:
  - name: AzureServiceConnection
    value: 'portfolio'
  - name: Location  
    value: 'westeurope'
  - name: ResourceGroupName
    value: 'portfolioRGWestEU'  # Static RG name
  - name: Suffix
    value: ''  # Still needed for resource name uniqueness
  - name: DevOpsRepoUrl
    value: 'https://dev.azure.com/chxgbx/portfolio/_git/portfolio'
  - name: DevOpsBranch
    value: 'staging'
  - name: EnablePurgeProtection
    value: 'false'
  - name: EnableRunFromPackage
    value: 'true'
  - group: portfolio-secrets

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Validate_Infrastructure
    displayName: "Validate Infrastructure"
    jobs:
      - job: validate_bicep
        displayName: "Validate Bicep Template"
        steps:
          - checkout: self
            fetchDepth: "1"

          # Still generate suffix for resource names, but not for RG
          - script: |
              if [ -z "$(Suffix)" ]; then
                RAND=$(tr -dc a-z0-9 </dev/urandom | head -c 6)
                echo "Generated suffix for validation: $RAND"
                echo "##vso[task.setvariable variable=GeneratedSuffix]$RAND"
              else
                echo "Using provided suffix: $(Suffix)"
                echo "##vso[task.setvariable variable=GeneratedSuffix]$(Suffix)"
              fi
            displayName: "Generate suffix"

          # Validate Bicep template with static RG
          - task: AzureCLI@2
            displayName: "Validate Bicep Template"
            inputs:
              azureSubscription: '$(AzureServiceConnection)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                
                echo "Validating Bicep template for Resource Group: $(ResourceGroupName)"
                
                # What-if deployment to preview changes
                az deployment group what-if \
                  --resource-group "$(ResourceGroupName)" \
                  --template-file infra/main.bicep \
                  --parameters \
                    location="$(Location)" \
                    suffix="$(GeneratedSuffix)" \
                    devOpsRepoUrl="$(DevOpsRepoUrl)" \
                    devOpsBranch="$(DevOpsBranch)" \
                    enablePurgeProtection=$(EnablePurgeProtection) \
                    enableRunFromPackage=$(EnableRunFromPackage) \
                  --only-show-errors || true
                
                echo "✅ Bicep template validation completed"
            env:
              AZURE_CORE_ONLY_SHOW_ERRORS: "true"

  - stage: Deploy_Infrastructure
    displayName: "Deploy Infrastructure"
    dependsOn: Validate_Infrastructure
    condition: and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'],'refs/heads/feature/infra-test'),
          eq(variables['Build.SourceBranch'],'refs/heads/main')
        )
      )
    jobs:
      - job: deploy_bicep
        displayName: "Deploy Bicep Template"
        steps:
          - checkout: self
            fetchDepth: "1"

          # Still generate suffix for resource names
          - script: |
              if [ -z "$(Suffix)" ]; then
                RAND=$(tr -dc a-z0-9 </dev/urandom | head -c 6)
                echo "Generated suffix: $RAND"
                echo "##vso[task.setvariable variable=GeneratedSuffix]$RAND"
              else
                echo "Using provided suffix: $(Suffix)"
                echo "##vso[task.setvariable variable=GeneratedSuffix]$(Suffix)"
              fi
            displayName: "Generate suffix"

          # Deploy infrastructure with static RG and existence check
          - task: AzureCLI@2
            displayName: "Deploy Bicep Template"
            inputs:
              azureSubscription: '$(AzureServiceConnection)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -euo pipefail

                # Check if RG exists and create only if it doesn't
                if ! az group show --name "$(ResourceGroupName)" --query "name" --output tsv 2>/dev/null; then
                  echo "Creating Resource Group: $(ResourceGroupName)"
                  az group create --name "$(ResourceGroupName)" --location "$(Location)" --only-show-errors
                else
                  echo "Resource Group $(ResourceGroupName) already exists"
                fi

                # Function to retry a command up to N times
                retry() {
                  local retries=$1
                  shift
                  local count=0
                  until "$@"; do
                    exit=$?
                    count=$((count + 1))
                    if [ $count -lt $retries ]; then
                      echo "Command failed. Attempt $count/$retries. Retrying in 5 seconds..."
                      sleep 5
                    else
                      return $exit
                    fi
                  done
                  return 0
                }

                # Run deployment - separate deployment from output capture
                echo "Deploying Bicep template..."
                retry 3 az deployment group create \
                  --name main \
                  --resource-group "$(ResourceGroupName)" \
                  --template-file infra/main.bicep \
                  --parameters \
                    location='$(Location)' \
                    suffix='$(GeneratedSuffix)' \
                    devOpsRepoUrl='$(DevOpsRepoUrl)' \
                    devOpsBranch='$(DevOpsBranch)' \
                    enablePurgeProtection=$(EnablePurgeProtection) \
                    enableRunFromPackage=$(EnableRunFromPackage) \
                  --mode Incremental \
                  --only-show-errors

                # Separate command to get outputs after successful deployment
                echo "✅ Bicep deployment succeeded. Retrieving outputs..."
                DEPLOY_OUTPUTS=$(az deployment group show \
                  --resource-group "$(ResourceGroupName)" \
                  --name main \
                  --query "properties.outputs" \
                  --output json)

                # Process outputs
                echo "$DEPLOY_OUTPUTS" > /tmp/deploy_outputs.json

                # Display outputs
                if [ -s /tmp/deploy_outputs.json ] && [ "$DEPLOY_OUTPUTS" != "{}" ]; then
                  echo "📊 Deployment outputs:"
                  echo "$DEPLOY_OUTPUTS" | jq -r 'to_entries[] | "  \(.key): \(.value.value)"' || true
                else
                  echo "  No outputs available"
                fi

                # Set pipeline outputs with static RG name
                echo "##vso[task.setvariable variable=FunctionAppName;isOutput=true]fa-portfolio-$(GeneratedSuffix)"
                echo "##vso[task.setvariable variable=ResourceGroupName;isOutput=true]$(ResourceGroupName)"
                echo "##vso[task.setvariable variable=StorageAccountName;isOutput=true]stportfolio$(GeneratedSuffix)"
                echo "##vso[task.setvariable variable=KeyVaultName;isOutput=true]kv-portfolio-$(GeneratedSuffix)"
                echo "##vso[task.setvariable variable=StaticWebAppName;isOutput=true]swa-portfolio-$(GeneratedSuffix)"
            env:
              AZURE_CORE_ONLY_SHOW_ERRORS: "true"

          # Show Deployment Outputs with static RG
          - task: AzureCLI@2
            displayName: "Show Deployment Outputs"
            inputs:
              azureSubscription: '$(AzureServiceConnection)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "🔍 Deployment Summary:"
                echo "=========================="
                
                # Get deployment outputs
                OUTPUTS=$(az deployment group show \
                  --resource-group "$(ResourceGroupName)" \
                  --name main \
                  --query "properties.outputs" \
                  --output json 2>/dev/null || echo "{}")
                
                if [ "$OUTPUTS" != "{}" ]; then
                  echo "📊 Outputs:"
                  echo "$OUTPUTS" | jq -r 'to_entries[] | "  \(.key): \(.value.value)"'
                else
                  echo "  No outputs available"
                fi
                
                echo ""
                echo "🔑 Key Vault Secrets to Add:"
                echo "  az keyvault secret set --vault-name kv-portfolio-$(GeneratedSuffix) --name GROQ-API-KEY --value '<your-groq-key>'"
                echo "  az keyvault secret set --vault-name kv-portfolio-$(GeneratedSuffix) --name GITHUB-TOKEN --value '<your-github-token>'"
